version: '3.8'

services:
 php:
  image: php:7.2-apache
  ports: 
  - 8006:80
  volumes:
  - ./:/var/www/html
  - ./form:/var/www/html/form
  - ./profile:/var/www/html/profile
  depends_on:
  - phpdb

 phpdb:
  image: mysql:5.7
  restart: always
  ports:
  - "3304:3308"
  environment:
    MYSQL_ROOT_PASSWORD: myrootpassword
    MYSQL_DATABASE: phpdb
    MYSQL_USER: phpdb
    MYSQL_PASSWORD: phppass





